# 网络安全检测配置文件
# 所有时间单位均为分钟，IP支持CIDR格式

# 允许登录的IP白名单（将不会触发非授权IP告警）
allowed_ips:
  - "192.168.1.0/24"    # 办公室内网段
  - "10.0.0.1/28"       # 服务器专用网段
  - "172.16.1.100"      # 特定管理主机
  - "-"

# 工作时间设置（用于检测非工作时间登录）
working_hours:
  start: "09:00"        # 上班时间（24小时制）
  end: "16:00"          # 下班时间
  # 注意：时间格式必须为 HH:MM
  # 周末自动视为非工作时间

# 检测阈值配置
thresholds:
  # 暴力破解检测配置
  brute_force:
    attempts: 10        # 在指定时间内允许的最大失败尝试次数
    minutes: 5          # 检测时间窗口（单位：分钟）
    # 典型值：5分钟内10次失败登录触发告警

  # 横向移动检测配置
  lateral_movement:
    users: 5            # 同一IP登录的不同用户数量阈值
    minutes: 60         # 检测时间窗口
    # 典型值：1小时内同一IP登录5个不同用户触发告警

# 特权账户列表（这些账户的登录会触发特权滥用检测）
privileged_accounts:
  - "Administrator"     # Windows管理员账户
  - "SYSTEM"            # 系统服务账户
  - "root"              # Linux根账户
  - "DBAccess"          # 数据库管理账户
  - "BackupAdmin"       # 备份管理账户

# 高级配置（谨慎修改）
advanced:
  log_retention_days: 30   # 分析日志保留天数
  csv_encoding: "utf-8"    # 生成的CSV文件编码格式
  timezone: "+08:00"       # 时区设置（需与日志时间一致）

# 使用说明：
# 1. 修改IP白名单后需重新启动分析程序
# 2. 工作时间设置支持多时段（需修改代码实现）
# 3. 特权账户列表建议包含所有Domain Admin账户
